# Generated by Django 4.2.1 on 2023-07-27 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('db_id', models.IntegerField(default=None)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('overview', models.CharField(blank=True, max_length=250, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('original_title', models.CharField(blank=True, max_length=50, null=True)),
                ('original_language', models.CharField(blank=True, max_length=50, null=True)),
                ('genre_ids', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
